ARCH:=x86
OS:=osx

LIBMOEPGF:=libmoepgf.a
LIBMOEPGFDIR:=src

LIBMOEPGFBENCH:=libmoepgfbench
LIBMOEPGFBENCHDIR:=benchmark

CFLAGS:= -O2 -Wall -Wextra
CC:=gcc
AR:=ar
ARFLAGS:=rcs
LDFLAGS:=
TARGET:=libmoepgf.a


